### ISSUE TITLE
implement colorscheme

### ISSUE THREAD

**Issue by david-wolgemuth** [david-wolgemuth/xyzplore#1]
# Juniper

### Color Scheme

![Screenshot_20240606-183935](https://github.com/david-wolgemuth/xyzplore/assets/11606807/79d8bf59-9a41-4b3f-a8bb-da2fde3a9db1)

- **Color 1**: ![#182039](https://via.placeholder.com/15/182039/000000?text=+) `#182039`
- **Color 2**: ![#3A5069](https://via.placeholder.com/15/3A5069/000000?text=+) `#3A5069`
- **Color 3**: ![#6D8AA3](https://via.placeholder.com/15/6D8AA3/000000?text=+) `#6D8AA3`
- **Color 4**: ![#96B0C7](https://via.placeholder.com/15/96B0C7/000000?text=+) `#96B0C7`
- **Color 5**: ![#C2CFDA](https://via.placeholder.com/15/C2CFDA/000000?text=+) `#C2CFDA`
- **Color 6**: ![#E1E8F0](https://via.placeholder.com/15/E1E8F0/000000?text=+) `#E1E8F0`
- **Color 7**: ![#2E2D2F](https://via.placeholder.com/15/2E2D2F/000000?text=+) `#2E2D2F`
- **Color 8**: ![#544741](https://via.placeholder.com/15/544741/000000?text=+) `#544741`
- **Color 9**: ![#87796E](https://via.placeholder.com/15/87796E/000000?text=+) `#87796E`
- **Color 10**: ![#AB9482](https://via.placeholder.com/15/AB9482/000000?text=+) `#AB9482`
- **Color 11**: ![#D6B8A4](https://via.placeholder.com/15/D6B8A4/000000?text=+) `#D6B8A4`
- **Color 12**: ![#EFCEBB](https://via.placeholder.com/15/EFCEBB/000000?text=+) `#EFCEBB`
- **Color 13**: ![#1B6D36](https://via.placeholder.com/15/1B6D36/000000?text=+) `#1B6D36`
- **Color 14**: ![#388E50](https://via.placeholder.com/15/388E50/000000?text=+) `#388E50`
- **Color 15**: ![#67B475](https://via.placeholder.com/15/67B475/000000?text=+) `#67B475`
- **Color 16**: ![#97D6A0](https://via.placeholder.com/15/97D6A0/000000?text=+) `#97D6A0`

**Comment by david-wolgemuth** [comment]
### Color Scheme for Juniper Mackenzie

- **Green**: ![#388E50](https://via.placeholder.com/15/388E50/000000?text=+) `#388E50`
- **Orange**: ![#D6B8A4](https://via.placeholder.com/15/D6B8A4/000000?text=+) `#D6B8A4`
- **Red**: ![#AB9482](https://via.placeholder.com/15/AB9482/000000?text=+) `#AB9482`
- **Blue**: ![#6D8AA3](https://via.placeholder.com/15/6D8AA3/000000?text=+) `#6D8AA3`

**Comment by david-wolgemuth** [comment]
### Color Scheme with Related Hex Codes

#### Orange
- **Primary Hex**: ![#D6B8A4](https://via.placeholder.com/15/D6B8A4/000000?text=+) `#D6B8A4`
- **Related Hex Codes**: 
  - ![#FFA500](https://via.placeholder.com/15/FFA500/000000?text=+) `#FFA500` (Orange)
  - ![#FF8C00](https://via.placeholder.com/15/FF8C00/000000?text=+) `#FF8C00` (Dark Orange)
  - ![#FF4500](https://via.placeholder.com/15/FF4500/000000?text=+) `#FF4500` (Orange Red)

#### Red
- **Primary Hex**: ![#AB9482](https://via.placeholder.com/15/AB9482/000000?text=+) `#AB9482`
- **Related Hex Codes**:
  - ![#FF0000](https://via.placeholder.com/15/FF0000/000000?text=+) `#FF0000` (Red)
  - ![#DC143C](https://via.placeholder.com/15/DC143C/000000?text=+) `#DC143C` (Crimson)
  - ![#B22222](https://via.placeholder.com/15/B22222/000000?text=+) `#B22222` (Firebrick)

#### Green
- **Primary Hex**: ![#388E50](https://via.placeholder.com/15/388E50/000000?text=+) `#388E50`
- **Related Hex Codes**:
  - ![#008000](https://via.placeholder.com/15/008000/000000?text=+) `#008000` (Green)
  - ![#32CD32](https://via.placeholder.com/15/32CD32/000000?text=+) `#32CD32` (Lime Green)
  - ![#228B22](https://via.placeholder.com/15/228B22/000000?text=+) `#228B22` (Forest Green)

#### Blue
- **Primary Hex**: ![#6D8AA3](https://via.placeholder.com/15/6D8AA3/000000?text=+) `#6D8AA3`
- **Related Hex Codes**:
  - ![#0000FF](https://via.placeholder.com/15/0000FF/000000?text=+) `#0000FF` (Blue)
  - ![#1E90FF](https://via.placeholder.com/15/1E90FF/000000?text=+) `#1E90FF` (Dodger Blue)
  - ![#4682B4](https://via.placeholder.com/15/4682B4/000000?text=+) `#4682B4` (Steel Blue)

**Comment by david-wolgemuth** [comment]
### Related Emojis

- **Orange**: 🟧 🍊 🥕 🧡 🦊 
- **Red**: 🟥 🍎 🍒 🍓 ❤️ 🦀 
- **Green**: 🟩 🍏 🥝 🌲 💚 🐢 
- **Blue**: 🪻 🟦 🌊 🦋 💙 🌀

**Comment by david-wolgemuth** [comment]
### Color Scheme with Related Hex Codes

#### Orange
- **Primary Hex**: ![#D6B8A4](https://via.placeholder.com/15/D6B8A4/000000?text=+) `#D6B8A4`
- **Related Hex Codes**: 
  - ![#FFA500](https://via.placeholder.com/15/FFA500/000000?text=+) `#FFA500` (Orange)
  - ![#FF8C00](https://via.placeholder.com/15/FF8C00/000000?text=+) `#FF8C00` (Dark Orange)
  - ![#FF4500](https://via.placeholder.com/15/FF4500/000000?text=+) `#FF4500` (Orange Red)

#### Red
- **Primary Hex**: ![#AB9482](https://via.placeholder.com/15/AB9482/000000?text=+) `#AB9482`
- **Related Hex Codes**:
  - ![#FF0000](https://via.placeholder.com/15/FF0000/000000?text=+) `#FF0000` (Red)
  - ![#DC143C](https://via.placeholder.com/15/DC143C/000000?text=+) `#DC143C` (Crimson)
  - ![#B22222](https://via.placeholder.com/15/B22222/000000?text=+) `#B22222` (Firebrick)

#### Green
- **Primary Hex**: ![#388E50](https://via.placeholder.com/15/388E50/000000?text=+) `#388E50`
- **Related Hex Codes**:
  - ![#008000](https://via.placeholder.com/15/008000/000000?text=+) `#008000` (Green)
  - ![#32CD32](https://via.placeholder.com/15/32CD32/000000?text=+) `#32CD32` (Lime Green)
  - ![#228B22](https://via.placeholder.com/15/228B22/000000?text=+) `#228B22` (Forest Green)

#### Blue
- **Primary Hex**: ![#6D8AA3](https://via.placeholder.com/15/6D8AA3/000000?text=+) `#6D8AA3`
- **Related Hex Codes**:
  - ![#0000FF](https://via.placeholder.com/15/0000FF/000000?text=+) `#0000FF` (Blue)
  - ![#1E90FF](https://via.placeholder.com/15/1E90FF/000000?text=+) `#1E90FF` (Dodger Blue)
  - ![#4682B4](https://via.placeholder.com/15/4682B4/000000?text=+) `#4682B4` (Steel Blue)

**Comment by w-divad-9142** [comment]
```css
:root {
  /* Orange Color Scheme */
  --orange-primary: #D6B8A4;
  --orange-related-1: #FFA500; /* Orange */
  --orange-related-2: #FF8C00; /* Dark Orange */
  --orange-related-3: #FF4500; /* Orange Red */

  /* Red Color Scheme */
  --red-primary: #AB9482;
  --red-related-1: #FF0000; /* Red */
  --red-related-2: #DC143C; /* Crimson */
  --red-related-3: #B22222; /* Firebrick */

  /* Green Color Scheme */
  --green-primary: #388E50;
  --green-related-1: #008000; /* Green */
  --green-related-2: #32CD32; /* Lime Green */
  --green-related-3: #228B22; /* Forest Green */

  /* Blue Color Scheme */
  --blue-primary: #6D8AA3;
  --blue-related-1: #0000FF; /* Blue */
  --blue-related-2: #1E90FF; /* Dodger Blue */
  --blue-related-3: #4682B4; /* Steel Blue */
}
```

**Comment by david-wolgemuth** [comment]
```css
:root {
    /* Neutral Color Scheme */
    --dark-gray: #27282e;
    --medium-dark-gray: #29292b;
    --slate-gray: #272629;
    --dark-slate-gray: #242625;
    --charcoal-gray: #212322;
    --slightly-darker-gray: #232524;
    --almost-black: #262828;
    --gray: #4c4e4d;
  
    /* Green and Blue Color Scheme */
    --olive-green: #597f1a;
    --light-blue: #4cb0d6;
    --sky-blue: #43afdd;
    --cerulean-blue: #37a0d1;
    --aqua-blue: #3ca0ce;
    --brick-red: #9c2f27;
    --dark-red: #992f28;
    --orange: #f7763b;
  
    /* Additional Colors */
    --olive-drab: #72913e;
    --pale-blue: #71b6ce;
    --light-cyan: #71b4d1;
    --sea-blue: #5eaacb;
    --sky-turquoise: #61acc5;
    --dark-brick-red: #8c2921;
    --deep-red: #811b1f;
    --burnt-orange: #df7944;
  
    /* Light Colors */
    --off-white: #fcfffe;
    --white-smoke: #fcffff;
    --pure-white-1: #fcffff;
    --pure-white-2: #fcffff;
    --ivory: #fcffff;
    --white-1: #ffffff;
    --white-2: #ffffff;
    --white-3: #ffffff;
  
    /* Dark Blue Color Scheme */
    --navy-blue: #0c3766;
    --deep-sea-blue: #175878;
    --slate-blue: #295a6f;
    --prussian-blue: #143751;
    --steel-blue: #0e4e6f;
    --dark-steel-blue: #114467;
    --midnight-blue: #0e2e4c;
    --dark-midnight-blue: #11284b;
  }
  ```
  

- Neutral Color Scheme */
    - dark-gray: `#27282e`
    - medium-dark-gray: `#29292b`
    - slate-gray: `#272629`
    - dark-slate-gray: `#242625`
    - charcoal-gray: `#212322`
    - slightly-darker-gray: `#232524`
    - almost-black: `#262828`
    - gray: `#4c4e4d`
- Green and Blue Color Scheme */
    - olive-green: `#597f1a`
    - light-blue: `#4cb0d6`
    - sky-blue: `#43afdd`
    - cerulean-blue: `#37a0d1`
    - aqua-blue: `#3ca0ce`
    - brick-red: `#9c2f27`
    - dark-red: `#992f28`
    - orange: `#f7763b`
- Additional Colors */
    - olive-drab: `#72913e`
    - pale-blue: `#71b6ce`
    - light-cyan: `#71b4d1`
    - sea-blue: `#5eaacb`
    - sky-turquoise: `#61acc5`
    - dark-brick-red: `#8c2921`
    - deep-red: `#811b1f`
    - burnt-orange: `#df7944`
- Light Colors */
    - off-white: `#fcfffe`
    - white-smoke: `#fcffff`
    - pure-white-1: `#fcffff`
    - pure-white-2: `#fcffff`
    - ivory: `#fcffff`
    - white-1: `#ffffff`
    - white-2: `#ffffff`
    - white-3: `#ffffff`
- Dark Blue Color Scheme */
    - navy-blue: `#0c3766`
    - deep-sea-blue: `#175878`
    - slate-blue: `#295a6f`
    - prussian-blue: `#143751`
    - steel-blue: `#0e4e6f`
    - dark-steel-blue: `#114467`
    - midnight-blue: `#0e2e4c`
    - dark-midnight-blue: `#11284b`
